### ISSUE TITLE
PyAMPA Running for the last 4 days 

### ISSUE THREAD

**Issue by Ahmer1122** [SysBioUAB/PyAMPA#2]
I am running PyAMPA on my isolated bacterial proteome. However, the pipeline has been running since the last  4 days.
My Workstation specs are i9-11900K @3.50Hz, 64 GB RAM.   How long does it usually take to analyze a bacterial proteome having 4000 protein sequences?

**Comment by SysBioUAB** [comment]
PyAMPA is very fast and should not take more than 1h to analyze a full proteome. Without more information, I would suggest to restart the computer and launch PyAMPA again. PyAMPA was tested under Linux, Windows and MACOS and now differences were found regarding execution time.
If you have more details, you can post it here and we will try to help you further.

Best regards,

PyAMPA Team
