### ISSUE TITLE
Results explanation problem

### ISSUE THREAD

**Issue by aslangabriel** [SysBioUAB/PyAMPA#3]
My test results were as follows:
![image](https://github.com/user-attachments/assets/fe1e45d0-8889-43a3-9c5a-8291bdcb8ab5)
![image](https://github.com/user-attachments/assets/6bb3d799-9931-4d43-a96c-16f762740330)
![image](https://github.com/user-attachments/assets/02519bc3-f7ff-470b-b684-85c2e502e24a)
my questions were listed as follows:
1、what does avg torrent index and amp validated prob mean? shoud I select candidates meets both needs of higher values; 
2、are there  any cut-off values for the scores of each bacteria? Should I choose the one with high values?
3、for the last image, what does the direction of arrows mean and what does the numbers in the inner ring mean? there is no explanation for the numbers?
4、Can I use the optimized sequenece to iterate design to get better candidates?
thanks a lot.

**Comment by SysBioUAB** [comment]
Thank you for using PyAMPA. Here are the answers to your questions:

1. Avg Torrent index refers to the average propensity index for the peptide. While lower values are generally better, this is not predictive of antimicrobial activity. The AMPValidate probability, on the other hand, is the probability of the peptide being an AMP according to our predictor, and it offers higher accuracy than the average Torrent index.
2. The values shown are the predicted MICs (minimum inhibitory concentrations) for each bacterium, where lower values indicate better predicted efficacy.
3. The arrows represent the direction of the hydrophobic moment of the helix, while the numbers denote the magnitude of the hydrophobic moment.
4. Yes, you can iterate to find better candidates. However, note that the results depend on your specific objectives. By default, PyAMPA uses the following optimization function:
F = wA⋅PA + wH⋅PH + wHL⋅HLNorm

This means you might want to adjust or explore different weights based on your interests. For more details on how the weights and optimization function work, please refer to the manuscript.
